user_defined_plugin_mappings = {
    "plugin_mappings": [
        {
            "plugin_name": "Analog Lab V",
            "parameters": [
                {"parameter_index": 2, "name": "Encoder 1"},
                {"parameter_index": 4, "name": "Encoder 2"},
                {"parameter_index": 6, "name": "Encoder 3"},
                {"parameter_index": 8, "name": "Encoder 4"},
                {"parameter_index": 1, "name": "Encoder 5"},
                {},
                {},
                {},
                {"parameter_index": 12, "name": "Fader 1"},
                {"parameter_index": 13, "name": "Fader 2"},
                {"parameter_index": 14, "name": "Fader 3"},
                {"parameter_index": 15, "name": "Fader 4"},
                {"parameter_index": 16, "name": "Fader 5"},
                {"parameter_index": 17, "name": "Fader 6"},
                {"parameter_index": 18, "name": "Fader 7"},
                {"parameter_index": 19, "name": "Fader 8"},
                {},
                {},
                {},
                {},
                {},
                {},
                {"parameter_index": 20, "name": "Mix"},
                {"parameter_index": 0, "name": "Master Volume"},
            ],
        },
        {
            "plugin_name": "Massive X",
            "parameters": [
                {"parameter_index": 0, "name": "Macro 1"},
                {"parameter_index": 1, "name": "Macro 2"},
                {"parameter_index": 2, "name": "Macro 3"},
                {"parameter_index": 3, "name": "Macro 4"},
                {"parameter_index": 4, "name": "Macro 5"},
                {"parameter_index": 5, "name": "Macro 6"},
                {"parameter_index": 6, "name": "Macro 7"},
                {"parameter_index": 7, "name": "Macro 8"},
                {"parameter_index": 8, "name": "Macro 9"},
                {"parameter_index": 9, "name": "Macro 10"},
                {"parameter_index": 10, "name": "Macro 11"},
                {"parameter_index": 11, "name": "Macro 12"},
                {"parameter_index": 12, "name": "Macro 13"},
                {"parameter_index": 13, "name": "Macro 14"},
                {"parameter_index": 14, "name": "Macro 15"},
                {"parameter_index": 15, "name": "Macro 16"},
            ],
        },
        {
            "plugin_name": "Vital",
            "parameters": [
                {"parameter_index": 211, "name": "Macro 1"},
                {"parameter_index": 212, "name": "Macro 2"},
                {"parameter_index": 213, "name": "Macro 3"},
                {"parameter_index": 214, "name": "Macro 4"},
            ],
        },
        {
            "plugin_name": "Surge XT",
            "parameters": [
                {"parameter_index": 0, "name": "Macro 1"},
                {"parameter_index": 1, "name": "Macro 2"},
                {"parameter_index": 2, "name": "Macro 3"},
                {"parameter_index": 3, "name": "Macro 4"},
                {"parameter_index": 4, "name": "Macro 5"},
                {"parameter_index": 5, "name": "Macro 6"},
                {"parameter_index": 6, "name": "Macro 7"},
                {"parameter_index": 7, "name": "Macro 8"},
                {"parameter_index": 8, "name": "FX 1 Return"},
                {"parameter_index": 9, "name": "FX 2 Return"},
                {"parameter_index": 10, "name": "FX 3 Return"},
                {"parameter_index": 11, "name": "FX 4 Return"},
                {},
                {},
                {},
                {"parameter_index": 12, "name": "Global Volume"},
            ],
        },
    ],
}
